<a href="https://colab.research.google.com/github/AmanIITP/Deep-Learning/blob/main/Regression_Backpropagation_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','score','lpa'])

In [4]:
df.head()

cgpa  score  lpa
0     8      8    4
1     7      9    5
2     6     10    6
3     5     12    7

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


In [7]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.get_weights()

[array([[-1.1796522 ,  0.6659101 ],
        [-0.75053316, -0.9370693 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.8617641],
        [0.7240232]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [16]:
model.fit(df.iloc[:,0:-1].values,df.iloc[:,-1].values,epochs=10,verbose=1,batch_size=1)

Epoch 1/10
4/4 [==============================] - 0s 3ms/step - loss: 2.3628
Epoch 2/10
4/4 [==============================] - 0s 3ms/step - loss: 2.3526
Epoch 3/10
4/4 [==============================] - 0s 4ms/step - loss: 2.3520
Epoch 4/10
4/4 [==============================] - 0s 4ms/step - loss: 2.3474
Epoch 5/10
4/4 [==============================] - 0s 3ms/step - loss: 2.3443
Epoch 6/10
4/4 [==============================] - 0s 3ms/step - loss: 2.3425
Epoch 7/10
4/4 [==============================] - 0s 3ms/step - loss: 2.3332
Epoch 8/10
4/4 [==============================] - 0s 4ms/step - loss: 2.3321
Epoch 9/10
4/4 [==============================] - 0s 3ms/step - loss: 2.3335
Epoch 10/10
4/4 [==============================] - 0s 3ms/step - loss: 2.3276


In [17]:
model.get_weights()

[array([[-0.7330709 ,  1.2050306 ],
        [-0.00689703,  0.14102095]], dtype=float32),
 array([0.6213396, 0.8556087], dtype=float32),
 array([[0.3497043 ],
        [0.59972566]], dtype=float32),
 array([0.8548645], dtype=float32)]